### ISSUE TITLE
Find cause of seg fault

### ISSUE THREAD

**Issue by quakeroatsgod** [Cyrus-Santiago/C.A.N.G.-Phys-Sim#68]
Right now the master branch will throw a segmentation fault whenever exiting the game. This occurs via pressing `Escape` or when pressing the exit button.

**Comment by FashionablyNate** [comment]
The dropAudioEngine method within audio.cpp was causing the segmentation fault. The issue was the engine got recreated every time a sound was played. I changed the class so that the engine is created upon construction of the audio object. I also altered the dropAudioEngine method to drop other sounds created before dropping the engine.
